<a href="https://colab.research.google.com/github/Gilgamesh60/-Unfinished-laptops-ratings-predictor/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100
df1=pd.read_csv('reviews.csv')
df2=pd.read_csv('laptops.csv')

In [ ]:
df1

,Review1,Review2,Review3,Review4,Review5,Ratings,feedback_counts,Description
0,Great Tablet at This Price,Must buy!,Fantastic purchase_Steps to get best performance,Terrific,Terrific purchase,4.0,"1,509 Ratings & 327 Reviews",This product tick all the boxes for the tablet...
1,Great product,Highly recommended,Simply awesome,Really Nice,Just wow!,3.5,869 Ratings & 105 Reviews,Design wise it's slim and easy to carry .. cam...
2,Nice,Decent product,Terrific purchase,Value-for-money,Great product,3.3,58 Ratings & 5 Reviews,"This Chromebook is very useful, simple, fast a..."
3,Fabulous!,Fabulous!,Pretty good,Battery backup is amazing!,Great product,3.5,"1,290 Ratings & 157 Reviews","Handy, smart, lightweight device. Good process..."
4,Best in the market!,Met my expectations except for the installed RAM.,Excellent,Fair,Highly recommended,3.6,"1,137 Ratings & 257 Reviews",Very much disappointing....I got it on 26 Sept...
...,...,...,...,...,...,...,...,...
931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932,NaN,NaN,NaN,NaN,Value-for-money,NaN,NaN,Awesome purchase!!!\n\nBuild quality: it's stu...
933,Worth every penny,Does the job,NaN,NaN,Awesome,4.3,7 Ratings & 0 Reviews,An affordable beast !\nPros:\n1. Incredible pe...
934,NaN,NaN,Don't waste your money,NaN,Just wow!,3.8,16 Ratings & 3 Reviews,"Battery life could be better , on normal usage..."
935,Mind-blowing purchase,Fabulous!,NaN,Value-for-money,NaN,NaN,NaN,NaN

In [ ]:
df2

,Company,model,RAM,storage,storage_type,Price
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",2,32,['SSD'],₹15190
1,HP,"['APU', 'Pro', 'A4', '']",4,32,"['EMMC', 'Storage']",₹16990
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",4,1,['HDD'],₹18890
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",2,32,"['EMMC', 'Storage']",₹18999
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",4,32,"['EMMC', 'Storage']",₹19174
...,...,...,...,...,...,...
931,HP,"['Spectre', 'x360', 'Core', 'i5', '11th', 'Gen...",1,512,['SSD'],₹86890
932,Lenovo,"['Yoga', 'Slim', '7', 'Intel', 'EVO', 'Core', ...",1,512,['SSD'],₹86990
933,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",1,1,['SSD'],₹86990
934,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",1,512,['SSD'],₹87000
935,HP,"['Pavilion', 'Core', 'i7', '12th', 'Gen', '']",1,512,['SSD'],₹87390

In [ ]:
import numpy as np
df=pd.concat([df2,df1],axis=1)

In [ ]:
df

,Company,model,RAM,storage,storage_type,Price,Review1,Review2,Review3,Review4,Review5,Ratings,feedback_counts,Description
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",2,32,['SSD'],₹15190,Great Tablet at This Price,Must buy!,Fantastic purchase_Steps to get best performance,Terrific,Terrific purchase,4.0,"1,509 Ratings & 327 Reviews",This product tick all the boxes for the tablet...
1,HP,"['APU', 'Pro', 'A4', '']",4,32,"['EMMC', 'Storage']",₹16990,Great product,Highly recommended,Simply awesome,Really Nice,Just wow!,3.5,869 Ratings & 105 Reviews,Design wise it's slim and easy to carry .. cam...
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",4,1,['HDD'],₹18890,Nice,Decent product,Terrific purchase,Value-for-money,Great product,3.3,58 Ratings & 5 Reviews,"This Chromebook is very useful, simple, fast a..."
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",2,32,"['EMMC', 'Storage']",₹18999,Fabulous!,Fabulous!,Pretty good,Battery backup is amazing!,Great product,3.5,"1,290 Ratings & 157 Reviews","Handy, smart, lightweight device. Good process..."
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",4,32,"['EMMC', 'Storage']",₹19174,Best in the market!,Met my expectations except for the installed RAM.,Excellent,Fair,Highly recommended,3.6,"1,137 Ratings & 257 Reviews",Very much disappointing....I got it on 26 Sept...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,HP,"['Spectre', 'x360', 'Core', 'i5', '11th', 'Gen...",1,512,['SSD'],₹86890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932,Lenovo,"['Yoga', 'Slim', '7', 'Intel', 'EVO', 'Core', ...",1,512,['SSD'],₹86990,NaN,NaN,NaN,NaN,Value-for-money,NaN,NaN,Awesome purchase!!!\n\nBuild quality: it's stu...
933,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",1,1,['SSD'],₹86990,Worth every penny,Does the job,NaN,NaN,Awesome,4.3,7 Ratings & 0 Reviews,An affordable beast !\nPros:\n1. Incredible pe...
934,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",1,512,['SSD'],₹87000,NaN,NaN,Don't waste your money,NaN,Just wow!,3.8,16 Ratings & 3 Reviews,"Battery life could be better , on normal usage..."
935,HP,"['Pavilion', 'Core', 'i7', '12th', 'Gen', '']",1,512,['SSD'],₹87390,Mind-blowing purchase,Fabulous!,NaN,Value-for-money,NaN,NaN,NaN,NaN

In [ ]:
def get_value_counts(col):
    print("Value Counts for ", col.name)
    print(col.value_counts())
    print("\n\n")
    
df.apply(get_value_counts)

Value Counts for  Company
ASUS         242
DELL         207
HP           169
Lenovo       163
acer          61
MSI           28
Avita         20
Infinix       20
LG             5
SAMSUNG        4
Nokia          4
Vaio           4
realme         4
RedmiBook      2
Micromax       1
Mi             1
APPLE          1
Name: Company, dtype: int64



Value Counts for  model
['Core', 'i3', '11th', 'Gen', '']                        44
['Core', 'i5', '11th', 'Gen', '']                        43
['Inspiron', 'Core', 'i5', '11th', 'Gen', '']            40
['Core', 'i3', '10th', 'Gen', '']                        21
['Inspiron', 'Core', 'i3', '11th', 'Gen', '']            13
                                                         ..
['Vostro', 'Ryzen', '5', 'Quad', 'Core', '3500U', '']     1
['Vivobook14', 'Core', 'i5', '11th', 'Gen', '']           1
['Aspire', '3', 'Core', 'i5', '10th', 'Gen', '']          1
['PureBook', 'X14', 'Core', 'i5', '10th', 'Gen', '']      1
['Pavilion', 'Core', 'i7', '12th', 'Gen', '']             1
Name: model, Length: 468, dtype: int64



Value Counts for  RAM
8    637
1    167
4    130
2      2
Name: RAM, dtype: int64



Value Counts for  storage
512    517
1      229
256    152
64      15
128     15
32       4
500      2
16       1
2        1
Name: storage, dtype: int64



Value Counts for  storage_type
['SSD']                693
['HDD']                219
['EMMC', 'Storage']     24
Name: storage_type, dtype: int64



Value Counts for  Price
₹59990    15
₹46990    14
₹62990    14
₹74990    13
₹64990    13
          ..
₹47790     1
₹47090     1
₹46900     1
₹46590     1
₹87390     1
Name: Price, Length: 430, dtype: int64



Value Counts for  Review1
Wonderful                                                       38
Perfect product!                                                32
Mind-blowing purchase                                           30
Simply awesome                                                  29
Worth every penny                                               29
Terrific purchase                                               26
Excellent                                                       24
Fabulous!                                                       24
Best in the market!                                             24
Must buy!                                                       21
Super!                                                          21
Just wow!                                                       18
Brilliant                                                       17
Good choice                                                     17
Pretty good                                                     16
Good quality product                                            16
Classy product                                                  16
Very Good                                                       16
Really Nice                                                     16
Highly recommended                                              15
Terrific                                                        15
Awesome                                                         13
Delightful                                                      12
Great product                                                   12
Worth the money                                                 10
Just okay                                                        7
Does the job                                                     7
Not recommended at all                                           7
Value-for-money                                                  6
Fair                                                             6
Good                                                             5
Horrible                                                         5
Nice product                                                     5
Decent product                                                   4
Did not meet expectations                                        4
Absolute rubbish!                                                3
Moderate                                                         3
Unsatisfactory                                                   2
Don't waste your money                                           2
Satisfactory                                                     2
Worth investing                                                  2
Waste of money!                                                  2
Amazing laptop!                                                  2
Terrible product                                                 2
Slightly disappointed                                            2
Best 2 in 1 upgradable laptop!                                   2
Hated it!                                                        2
Nice                                                             2
3 Months In and I am Fairly Satisfied                            2
Great machine at good price                                      1
Worst experience ever!                                           1
One of the best laptop from Lenovo. Worth the buy.               1
Performance Laptop it is.                                        1
Avarage                                                          1
Awesome, Excellent Good Cause too                                1
Worthless                                                        1
worth buy ( 1 day review )                                       1
Bad quality                                                      1
BEST LAPTOP UNDER 60K                                            1
PRODUCT FOR SPECIFIC CUSTOMERS ONLY                              1
Good Product                                                     1
Expected a better product                                        1
Not good                                                         1
BEST PRODUCT WITH GOOD BATTERY LIFE.BUT VERY POOR FOR GAMING     1
Best Gaming Laptop at 75k!!!! BUT beware of EKART!               1
Bank for your buck                                               1
Very poor                                                        1
Totally Worth iI!                                                1
Superb                                                           1
Awsome......Slim                                                 1
Love my Chromebook                                               1
superb deal.                                                     1
Detailed Information                                             1
Highly recommended but wait for upcoming mi laptop               1
Terrific Purchase                                                1
Good buy !                                                       1
The Best of 21000 rs Range                                       1
Satisfied                                                        1
VERY GOOD PRODUCT ONLY THROUGH "" FLIPKART ""                    1
Great product at this price range                                1
Most Honest and Longest Review After 3 Months Use!               1
Good laptop with great build and battery life , VFM              1
Useless product                                                  1
Powerful Budget Laptop..!!                                       1
Best for Web Browsing                                            1
Nice product with rocking specs                                  1
AWESOMEST ..CRAZIEST....MINDBLOWING                              1
Great Tablet at This Price                                       1
Name: Review1, dtype: int64



Value Counts for  Review2
Fabulous!                                                     31
Wonderful                                                     29
Perfect product!                                              25
Simply awesome                                                24
Just wow!                                                     23
Best in the market!                                           22
Worth every penny                                             20
Highly recommended                                            20
Must buy!                                                     19
Classy product                                                19
Terrific purchase                                             19
Awesome                                                       18
Very Good                                                     16
Value-for-money                                               15
Mind-blowing purchase                                         15
Brilliant                                                     15
Excellent                                                     14
Good quality product                                          14
Great product                                                 14
Super!                                                        13
Worth the money                                               12
Just okay                                                     11
Really Nice                                                   11
Terrific                                                      10
Pretty good                                                   10
Nice product                                                   9
Good choice                                                    8
Terrible product                                               7
Utterly Disappointed                                           6
Does the job                                                   6
Delightful                                                     5
Worthless                                                      5
Did not meet expectations                                      5
Absolute rubbish!                                              4
Not recommended at all                                         4
Nice                                                           4
Good                                                           4
Worst experience ever!                                         4
Decent product                                                 3
Moderate                                                       3
Bad quality                                                    3
Fair                                                           3
Useless product                                                3
Horrible                                                       2
Unsatisfactory                                                 2
Brilliant display with good performance                        2
Value-for-Money! but...                                        2
Excellent WFH/Kids Online class gadget with ONE MAJOR FLAW     1
The All in one package..!                                      1
Very very poor Customer support                                1
Sleek and stylish                                              1
Best in this price range                                       1
Slightly disappointed                                          1
Below expectation                                              1
ASUS TUF Gaming F15 Review                                     1
Hated it!                                                      1
Very Good Product                                              1
Truely value for money                                         1
Best Product                                                   1
Great Experience with Flipkart and a Good Purchase             1
Good one !!!!                                                  1
The beast is here !                                            1
Configuration is ok for this price                             1
Good laptop                                                    1
good for the budget but heating is on the higher side.         1
Most Affordable 2 in 1 Laptop                                  1
Waste of money!                                                1
Better install Win 10 to enjoy performance                     1
Expected a better product                                      1
Super! Worth to buy!                                           1
Great Product                                                  1
Loved it                                                       1
Met my expectations except for the installed RAM.              1
Great for work                                                 1
Could be way better                                            1
Overall its an excellent deal!                                 1
Excellent Laptop in budget for beginners and next level        1
Four Stars                                                     1
Very poor                                                      1
Sweet and Sour combo                                           1
Name: Review2, dtype: int64



Value Counts for  Review3
Simply awesome                                                  27
Great product                                                   26
Highly recommended                                              24
Excellent                                                       24
Terrific purchase                                               23
Just wow!                                                       23
Best in the market!                                             21
Classy product                                                  21
Wonderful                                                       21
Super!                                                          19
Perfect product!                                                17
Awesome                                                         16
Brilliant                                                       16
Fabulous!                                                       15
Worth every penny                                               15
Delightful                                                      15
Terrific                                                        14
Value-for-money                                                 12
Really Nice                                                     11
Pretty good                                                     11
Good quality product                                            11
Must buy!                                                       10
Mind-blowing purchase                                           10
Good choice                                                      9
Did not meet expectations                                        8
Nice product                                                     8
Does the job                                                     7
Horrible                                                         6
Fair                                                             6
Don't waste your money                                           6
Very Good                                                        5
Not recommended at all                                           4
Utterly Disappointed                                             4
Worthless                                                        4
Expected a better product                                        4
Just okay                                                        4
Good                                                             4
Moderate                                                         4
Worst experience ever!                                           3
Nice                                                             3
Hated it!                                                        3
Unsatisfactory                                                   3
Worth the money                                                  3
Decent product                                                   3
Bad quality                                                      2
Beastly Notebook                                                 2
Absolute rubbish!                                                2
Useless product                                                  2
best best best ever i need i found...                            2
Waste of money!                                                  2
Not good                                                         2
Product is good with some major cons                             1
Good configuration laptop                                        1
Good for multitasking                                            1
Good but nothing fancy                                           1
Best light weight all-rounder laptop                             1
Worst experience.it doesn't give me feel of i7 7Gen              1
Fabulous Product                                                 1
4GB ram is a sin but product is good                             1
Fantastic purchase_Steps to get best performance                 1
Good purchase                                                    1
Best value for money                                             1
Meets Expectation.                                               1
Terrible product                                                 1
Could be way better                                              1
Good Product with GST issues                                     1
Very poor                                                        1
Great Laptop @ This Price ... But Worst Speaker Ever..!          1
Slightly disappointed                                            1
nice laptop                                                      1
Good Product, Build quality is good.........................     1
Best value for money in this price segment                       1
Name: Review3, dtype: int64



Value Counts for  Review4
Wonderful                                                       33
Terrific                                                        26
Terrific purchase                                               21
Super!                                                          19
Brilliant                                                       19
Excellent                                                       18
Awesome                                                         18
Classy product                                                  17
Simply awesome                                                  17
Fabulous!                                                       16
Great product                                                   15
Best in the market!                                             15
Delightful                                                      14
Value-for-money                                                 14
Nice product                                                    13
Perfect product!                                                13
Very Good                                                       12
Must buy!                                                       12
Highly recommended                                              11
Just wow!                                                       11
Worth the money                                                 10
Worth every penny                                                9
Good choice                                                      9
Really Nice                                                      9
Does the job                                                     8
Pretty good                                                      8
Mind-blowing purchase                                            7
Terrible product                                                 6
Moderate                                                         5
Nice                                                             5
Hated it!                                                        5
Decent product                                                   5
Useless product                                                  5

Company            None
model              None
RAM                None
storage            None
storage_type       None
Price              None
Review1            None
Review2            None
Review3            None
Review4            None
Review5            None
Ratings            None
feedback_counts    None
Description        None
dtype: object



Stuff to do


*  Handle missing ratings
*  convert feedback into two seperate columns no_of_reviews and no_of_ratings.\
* In storage, all are not in same unit. Like 1 ,2 are actually TB not GB. So replace them.
*  convert ratings into float
*  convert price integer 
*  convert storage_type into string
*  convert RAM into integer
*  convert storage_type into integer if not already
*  Due to problem in datascrapping,16 GB RAM is interpreted as 1 GB RAM
*  Review cleaning-clean the review strings for sentiment analysis.
*  Cleaning the description column for sentiment analysis

#Cleaning the numerical data

In [ ]:
df.dropna(subset=['Ratings'],inplace=True)
df

,Company,model,RAM,storage,storage_type,Price,Review1,Review2,Review3,Review4,Review5,Ratings,feedback_counts,Description
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",2,32,['SSD'],₹15190,Great Tablet at This Price,Must buy!,Fantastic purchase_Steps to get best performance,Terrific,Terrific purchase,4.0,"1,509 Ratings & 327 Reviews",This product tick all the boxes for the tablet...
1,HP,"['APU', 'Pro', 'A4', '']",4,32,"['EMMC', 'Storage']",₹16990,Great product,Highly recommended,Simply awesome,Really Nice,Just wow!,3.5,869 Ratings & 105 Reviews,Design wise it's slim and easy to carry .. cam...
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",4,1,['HDD'],₹18890,Nice,Decent product,Terrific purchase,Value-for-money,Great product,3.3,58 Ratings & 5 Reviews,"This Chromebook is very useful, simple, fast a..."
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",2,32,"['EMMC', 'Storage']",₹18999,Fabulous!,Fabulous!,Pretty good,Battery backup is amazing!,Great product,3.5,"1,290 Ratings & 157 Reviews","Handy, smart, lightweight device. Good process..."
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",4,32,"['EMMC', 'Storage']",₹19174,Best in the market!,Met my expectations except for the installed RAM.,Excellent,Fair,Highly recommended,3.6,"1,137 Ratings & 257 Reviews",Very much disappointing....I got it on 26 Sept...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,MSI,"['GF65', 'Thin', 'Core', 'i7', '10th', 'Gen', '']",1,1,['HDD'],₹85990,Simply awesome,Perfect product!,NaN,Absolute rubbish!,NaN,3.9,10 Ratings & 1 Reviews,NaN
928,ASUS,"['Zenbook', '14', 'OLED', '(2022)', 'Intel', '...",1,256,['SSD'],₹86000,Excellent,Perfect product!,NaN,Terrific,Worth every penny,4.1,120 Ratings & 21 Reviews,This laptop is a superb one. Amazing performan...
929,ASUS,"['Vivobook', 'Pro', '14', 'OLED', '(2021)', 'R...",8,512,['SSD'],₹86000,NaN,NaN,Fabulous!,NaN,NaN,4.4,84 Ratings & 9 Reviews,NaN
933,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",1,1,['SSD'],₹86990,Worth every penny,Does the job,NaN,NaN,Awesome,4.3,7 Ratings & 0 Reviews,An affordable beast !\nPros:\n1. Incredible pe...
934,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",1,512,['SSD'],₹87000,NaN,NaN,Don't waste your money,NaN,Just wow!,3.8,16 Ratings & 3 Reviews,"Battery life could be better , on normal usage..."

In [ ]:
#create an index column with 717 rows
df.set_index(pd.Index(range(725)),inplace=True)
df

,Company,model,RAM,storage,storage_type,Price,Review1,Review2,Review3,Review4,Review5,Ratings,feedback_counts,Description
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",2,32,['SSD'],₹15190,Great Tablet at This Price,Must buy!,Fantastic purchase_Steps to get best performance,Terrific,Terrific purchase,4.0,"1,509 Ratings & 327 Reviews",This product tick all the boxes for the tablet...
1,HP,"['APU', 'Pro', 'A4', '']",4,32,"['EMMC', 'Storage']",₹16990,Great product,Highly recommended,Simply awesome,Really Nice,Just wow!,3.5,869 Ratings & 105 Reviews,Design wise it's slim and easy to carry .. cam...
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",4,1,['HDD'],₹18890,Nice,Decent product,Terrific purchase,Value-for-money,Great product,3.3,58 Ratings & 5 Reviews,"This Chromebook is very useful, simple, fast a..."
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",2,32,"['EMMC', 'Storage']",₹18999,Fabulous!,Fabulous!,Pretty good,Battery backup is amazing!,Great product,3.5,"1,290 Ratings & 157 Reviews","Handy, smart, lightweight device. Good process..."
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",4,32,"['EMMC', 'Storage']",₹19174,Best in the market!,Met my expectations except for the installed RAM.,Excellent,Fair,Highly recommended,3.6,"1,137 Ratings & 257 Reviews",Very much disappointing....I got it on 26 Sept...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,MSI,"['GF65', 'Thin', 'Core', 'i7', '10th', 'Gen', '']",1,1,['HDD'],₹85990,Simply awesome,Perfect product!,NaN,Absolute rubbish!,NaN,3.9,10 Ratings & 1 Reviews,NaN
721,ASUS,"['Zenbook', '14', 'OLED', '(2022)', 'Intel', '...",1,256,['SSD'],₹86000,Excellent,Perfect product!,NaN,Terrific,Worth every penny,4.1,120 Ratings & 21 Reviews,This laptop is a superb one. Amazing performan...
722,ASUS,"['Vivobook', 'Pro', '14', 'OLED', '(2021)', 'R...",8,512,['SSD'],₹86000,NaN,NaN,Fabulous!,NaN,NaN,4.4,84 Ratings & 9 Reviews,NaN
723,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",1,1,['SSD'],₹86990,Worth every penny,Does the job,NaN,NaN,Awesome,4.3,7 Ratings & 0 Reviews,An affordable beast !\nPros:\n1. Incredible pe...
724,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",1,512,['SSD'],₹87000,NaN,NaN,Don't waste your money,NaN,Just wow!,3.8,16 Ratings & 3 Reviews,"Battery life could be better , on normal usage..."

In [ ]:
no_of_rating=[]
no_of_review=[]
for i in range(len(df['feedback_counts'])):
  try:
    no_of_rating.append(df['feedback_counts'][i].split(' ')[0])
  except:
    no_of_rating.append(np.nan)
  try:
    no_of_review.append(df['feedback_counts'][i].split('& ')[1].split(' ')[0])
  except:
    no_of_review.append(np.nan)

In [ ]:
df3=pd.DataFrame({'no_of_reviews':no_of_review,'no_of_ratings':no_of_rating})
df=pd.concat([df,df3],axis=1)
df

In [ ]:
df.replace({'storage':{1:1000,2:2000}},inplace=True)
df

In [ ]:
df.insert(2,'price',value=df['Price'].apply(lambda x: int(x.split('₹')[1])))

In [ ]:
df.insert(3,'R.A.M',value=df['RAM'].apply(lambda x: int(x)))
df.insert(4,'Total_storage',value=df['storage'].apply(lambda x: int(x)))

In [ ]:
df.replace({'R.A.M':{1:16}},inplace=True)

In [ ]:
def tointeger(l):
  try:
    r=l.split(',')
    sum=''
    for i in range(len(r)):
      sum=sum+r[i];
    return int(sum)
  except:
     return np.nan
def integer(l):
  try:
    return int(l);
  except:
    return np.nan
df.insert(5,'No_of_Ratings',df['no_of_ratings'].apply(lambda x: tointeger(x)))
df.insert(6,'No_of_Reviews',df['no_of_reviews'].apply(lambda x: integer(x)))


#Dropping unnecessary columns and renaming few elements for simplicity

In [ ]:
df['storage_type'].unique()

array(["['SSD']", "['EMMC', 'Storage']", "['HDD']"], dtype=object)

In [ ]:
df=df.replace({'storage_type':{"['SSD']":'SSD',"['EMMC', 'Storage']":'EMMC',"['HDD']":'HDD'}})

In [ ]:
df.dropna(subset=['feedback_counts'],inplace=True)

In [ ]:
df=df.drop(['RAM','Price','no_of_ratings','no_of_reviews','feedback_counts'],axis=1)

In [ ]:
df.dropna(subset=['No_of_Ratings'],inplace=True)

In [ ]:
df.set_index(pd.Index(range(714)),inplace=True)

In [ ]:
df

,Company,model,price,R.A.M,Total_storage,No_of_Ratings,No_of_Reviews,storage,storage_type,Review1,Review2,Review3,Review4,Review5,Ratings,Description
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",15190,2,32,1509.0,327.0,32,SSD,Great Tablet at This Price,Must buy!,Fantastic purchase_Steps to get best performance,Terrific,Terrific purchase,4.0,This product tick all the boxes for the tablet...
1,HP,"['APU', 'Pro', 'A4', '']",16990,4,32,869.0,105.0,32,EMMC,Great product,Highly recommended,Simply awesome,Really Nice,Just wow!,3.5,Design wise it's slim and easy to carry .. cam...
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",18890,4,1000,58.0,5.0,1000,HDD,Nice,Decent product,Terrific purchase,Value-for-money,Great product,3.3,"This Chromebook is very useful, simple, fast a..."
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",18999,2,32,1290.0,157.0,32,EMMC,Fabulous!,Fabulous!,Pretty good,Battery backup is amazing!,Great product,3.5,"Handy, smart, lightweight device. Good process..."
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",19174,4,32,1137.0,257.0,32,EMMC,Best in the market!,Met my expectations except for the installed RAM.,Excellent,Fair,Highly recommended,3.6,Very much disappointing....I got it on 26 Sept...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,MSI,"['GF65', 'Thin', 'Core', 'i7', '10th', 'Gen', '']",85990,16,1000,10.0,1.0,1000,HDD,Simply awesome,Perfect product!,NaN,Absolute rubbish!,NaN,3.9,NaN
710,ASUS,"['Zenbook', '14', 'OLED', '(2022)', 'Intel', '...",86000,16,256,120.0,21.0,256,SSD,Excellent,Perfect product!,NaN,Terrific,Worth every penny,4.1,This laptop is a superb one. Amazing performan...
711,ASUS,"['Vivobook', 'Pro', '14', 'OLED', '(2021)', 'R...",86000,8,512,84.0,9.0,512,SSD,NaN,NaN,Fabulous!,NaN,NaN,4.4,NaN
712,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",86990,16,1000,7.0,0.0,1000,SSD,Worth every penny,Does the job,NaN,NaN,Awesome,4.3,An affordable beast !\nPros:\n1. Incredible pe...
713,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",87000,16,512,16.0,3.0,512,SSD,NaN,NaN,Don't waste your money,NaN,Just wow!,3.8,"Battery life could be better , on normal usage..."

# Cleaning the review data so that we can perform sentiment analysis afterwards

In [ ]:
! pip install -q wordcloud
import wordcloud
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words= stopwords.words('english')

In [ ]:
##cleaning reviews for sentiment analysis
#(1)lowering the capital letters
#(2)replacing all the punctuation marks
#(3)deleting all the stop words
for i in range(5):
  df.replace({f'Review{i+1}':{np.nan:''}},inplace=True)
  df[f'Review{i+1}']=df[f'Review{i+1}'].apply(lambda x: " ".join(word.lower() for word in x.split()))
  df[f'Review{i+1}']=df[f'Review{i+1}'].str.replace('[^\w\s]','')
  df[f'Review{i+1}']=df[f'Review{i+1}'].apply(lambda x:" ".join(word for word in x.split() if word not in stop_words ))
df

#Cleaning description for sentiment analysis

In [ ]:
df['Description']

0      This product tick all the boxes for the tablet...
1      Design wise it's slim and easy to carry .. cam...
2      This Chromebook is very useful, simple, fast a...
3      Handy, smart, lightweight device. Good process...
4      Very much disappointing....I got it on 26 Sept...
                             ...
709                                                  NaN
710    This laptop is a superb one. Amazing performan...
711                                                  NaN
712    An affordable beast !\nPros:\n1. Incredible pe...
713    Battery life could be better , on normal usage...
Name: Description, Length: 714, dtype: object

In [ ]:
#converting NaN elements into string
df.replace({'Description':{np.nan:''}},inplace=True)

In [ ]:
# Removing Punctuations from the Review description
import string
def punctuation_removal(messy_str):
    clean_list = [char for char in messy_str if char not in string.punctuation]
    clean_str = ''.join(clean_list)
    return clean_str

df['Description'] = df['Description'].apply(punctuation_removal)

In [ ]:
# lets make a function to remove Numbers from the reviews
import re
def drop_numbers(list_text):
    list_text_new = []
    for i in list_text:
        if not re.search('\d', i):
            list_text_new.append(i)
    return ''.join(list_text_new)

df['Description'] = df['Description'].apply(drop_numbers)

In [ ]:
# lets create a function to remove accented characters
import unicodedata
def remove_accented_chars(text):
    new_text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    return new_text

# lets apply the function
df['Description'] = df.apply(lambda x: remove_accented_chars(x['Description']), axis = 1)

In [ ]:
# Create a function to remove special characters
def remove_special_characters(text):
    pat = r'[^a-zA-z0-9]' 
    return re.sub(pat, ' ', text)
 
# lets apply this function
df['Description'] = df.apply(lambda x: remove_special_characters(x['Description']), axis = 1)

In [ ]:
#lower all the capital characters and remove the 'read more' part at the end of few strings which is not necessary
df['Description']=df['Description'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df['Description']=df['Description'].apply(lambda x: x.split('read more')[0])

In [ ]:
df

,Company,model,price,R.A.M,Total_storage,No_of_Ratings,No_of_Reviews,storage,storage_type,Review1,Review2,Review3,Review4,Review5,Ratings,Description
0,acer,"['One', '10', 'Atom', 'Quad', 'Core', '']",15190,2,32,1509.0,327.0,32,SSD,great tablet price,must buy,fantastic purchase_steps get best performance,terrific,terrific purchase,4.0,this product tick all the boxes for the tablet...
1,HP,"['APU', 'Pro', 'A4', '']",16990,4,32,869.0,105.0,32,EMMC,great product,highly recommended,simply awesome,really nice,wow,3.5,design wise its slim and easy to carry camera ...
2,Lenovo,"['APU', 'Dual', 'Core', 'E2', 'E2-9000', '7th'...",18890,4,1000,58.0,5.0,1000,HDD,nice,decent product,terrific purchase,valueformoney,great product,3.3,this chromebook is very useful simple fast and...
3,Micromax,"['Canvas', 'Laptab', 'II', '(WIFI)', 'Atom', '...",18999,2,32,1290.0,157.0,32,EMMC,fabulous,fabulous,pretty good,battery backup amazing,great product,3.5,handy smart lightweight device good processing...
4,ASUS,"['Chromebook', 'Celeron', 'Dual', 'Core', '']",19174,4,32,1137.0,257.0,32,EMMC,best market,met expectations except installed ram,excellent,fair,highly recommended,3.6,very much disappointingi got it on september a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,MSI,"['GF65', 'Thin', 'Core', 'i7', '10th', 'Gen', '']",85990,16,1000,10.0,1.0,1000,HDD,simply awesome,perfect product,,absolute rubbish,,3.9,
710,ASUS,"['Zenbook', '14', 'OLED', '(2022)', 'Intel', '...",86000,16,256,120.0,21.0,256,SSD,excellent,perfect product,,terrific,worth every penny,4.1,this laptop is a superb one amazing performanc...
711,ASUS,"['Vivobook', 'Pro', '14', 'OLED', '(2021)', 'R...",86000,8,512,84.0,9.0,512,SSD,,,fabulous,,,4.4,
712,DELL,"['Vostro', 'Core', 'i5', '12th', 'Gen', '']",86990,16,1000,7.0,0.0,1000,SSD,worth every penny,job,,,awesome,4.3,an affordable beast pros incredible performanc...
713,Lenovo,"['IdeaPad', '5', 'Pro', 'Ryzen', '7', 'Hexa', ...",87000,16,512,16.0,3.0,512,SSD,,,dont waste money,,wow,3.8,battery life could be better on normal usage i...

--------------------------------------------

In [ ]:
df.to_csv('Complete_lsptopsdata.csv')